# Generated by Django 3.2.15 on 2022-10-09 08:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='post_image')),
                ('caption', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
