# Generated by Django 3.2.15 on 2022-10-09 21:04

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221009_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.IntegerField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
